### ISSUE TITLE
Validate if FabricID is set to 1 on all APICs , Spines and Leafs

### ISSUE THREAD

**Issue by kdebrouwer** [datacenter/ACI-Pre-Upgrade-Validation-Script#38] opened 2022-11-04 15:38 UTC
an APIC controller with a  a different Fabric ID then 1 can cause upgrade issues. 

This request is to add a validation check for topSystem and check if fabricId is set 1 for all APICs, Spines and Leafs

**Comment by cezaryborysiuk** [comment] 2022-11-08 10:42
FabricID might be other than "1" and this is not a bug. In some scenarios, FabricID must be unique between sites, so it must be different than "1". However, FabricID must be consistent across all APICs, Spines and Leaves in the site.

**Comment by takishida** [comment] 2023-08-17 03:19
@kdebrouwer 

I also think the check should be to confirm that the fabric ID is the same across all nodes in the same fabric (site) instead of being always 1.

What do you think? Any specific issue or defect that you have in mind?

I am thinking about CSCvn97710 which fixed the issue where APICs can no longer join the fabric after an upgrade due to inconsistent fabric IDs between APICs. But it's relatively old, that was fixed in a long-lived release of two generations ago (3.2). I'm wondering if you have newer issues that we need to capture?

**Comment by takishida** [comment] 2024-04-26 15:31
OP agreed to close this as there are no recent users impacted by this.

**Closed by takishida** 2024-04-26 15:31 UTC
Labels: new_validation
